apiVersion: template.openshift.io/v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: glusterfs-cluster
  spec:
    ports:
    - port: 1
      protocol: TCP
      targetPort: 1
- apiVersion: v1
  kind: Endpoints
  metadata:
    name: glusterfs-cluster
  subsets:
  - addresses:
    - ip: 172.17.176.30
    - ip: 172.17.176.31
    - ip: 172.17.176.32
    ports:
    - port: 1
      protocol: TCP
